### ISSUE TITLE
Ask about initialize_local function in g6k/kernel/control.cpp

### ISSUE THREAD

**Issue by Summwer** [fplll/g6k#100]
In around line 268 in g6k/kernel/control.cpp, why does rr[i] should factor gh to renormalize itself, could you please provide the theoretical basis?

And the following picture is the line which I doubt, thanks for giving an answer~
![image](https://user-images.githubusercontent.com/26530870/138043613-74f42e45-778c-4e3b-943f-921a37ee764e.png)

**Comment by lducas** [comment]
This is just for convenience. Later on, this allows to measure the length of vectors directly as a multiple of gh. For example, to measure saturation, we can just count vectors of "renormalized" squared norm less than 4/3.
