### ISSUE TITLE
Where is “./rebuild” ？

### ISSUE THREAD

**Issue by CRchengrong** [fplll/g6k#104]
UserWarning: Dimension of lattice is larger than maximum supported. To fix this warning, change the value of MAX_SIEVING_DIM in siever.h and recompile.

My matrix exceeds the maximum of 128, but I can't find a way to recompile

**Comment by malb** [comment]
This is a bug, thanks for reporting it.

**Comment by CRchengrong** [comment]
> This is a bug, thanks for reporting it.
Thank you for your reply, I followed the instructions, but the maximum limit is still there. What should I do to remove the limit?
`./configure --with-max-sieving-dim=512
python setup.py build_ext
`

**Comment by malb** [comment]
Can you try to do `make clean` and `python setup.py clean` before doing a rebuild using `python setup.py build_ext` ?

**Comment by CRchengrong** [comment]
> Can you try to do `make clean` and `python setup.py clean` before doing a rebuild using `python setup.py build_ext` ?

Yes, I tried 
```
make clean
./configure --with-max-sieving-dim=512
python setup.py clean
python setup.py build_ext
```
It still can't be modified. This is my test code：
```
from fpylll import IntegerMatrix
from g6k import Siever
res1 = Siever(IntegerMatrix.random(50, "qary", k=25, bits=10), seed=0x1337).max_sieving_dim
res2 = Siever(IntegerMatrix.random(200, "qary", k=25, bits=10), seed=0x1337).max_sieving_dim
```

**Comment by malb** [comment]
You are not running `python setup.py build_ext --inplace` but you're alos not running `python setup.py install`, so it might pick up the previously installed version?

**Comment by CRchengrong** [comment]
> You are not running `python setup.py build_ext --inplace` but you're alos not running `python setup.py install`, so it might pick up the previously installed version?

Amazing! This is the right way to compile, thanks for your answer!

**Comment by malb** [comment]
Ace. I've updated the README accordingly too. Thanks again for reporting this.
