### ISSUE TITLE
Issues with new install of G6K

### ISSUE THREAD

**Issue by nguyen-tuonghuy** [fplll/g6k#115]
Hello,

I was usually using the install procedure described here : [https://martinralbrecht.wordpress.com/2020/08/23/conda-jupyter-and-emacs/](url) using conda to install g6k.

Since, the rebuild.sh file has been removed, I went back to using the procedures described in the readme : using the bootstrap.sh or using an environment with already fplll/fpylll (which is analoguous to the conda procedure mentionned above).
However, none of the procedures worked.

I received the following error (using the second method with fpyll already installed) :

> $ python3 setup.py install
> 
> Compiling g6k/siever.pyx because it changed.
> Compiling g6k/siever_params.pyx because it changed.
> [1/2] Cythonizing g6k/siever.pyx
> warning: /home/tuong-huy/miniconda3/envs/env-g6k/lib/python3.11/site-packages/cysignals/signals.pxd:57:56: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
>             if lens[i] > 0.:
>                 L.append((i, lens[i], vecs[i]))
>         return L
> 
> 
>     def insert_best_lift(self, scoring=(lambda index, nlen, olen, aux: True), aux=None):
>                                         ^
> ------------------------------------------------------------
> 
> g6k/siever.pyx:1664:40: Compiler crash in ExpressionWriter
> 
> 
> Compiler crash traceback from this point on:
>   File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit
>   File "/home/tuong-huy/miniconda3/envs/env-g6k/lib/python3.11/site-packages/Cython/CodeWriter.py", line 512, in visit_Node
>     raise AssertionError("Node not handled by serializer: %r" % node)
> AssertionError: Node not handled by serializer: <Cython.Compiler.ExprNodes.LambdaNode object at 0x7f010a890550>
> Traceback (most recent call last):
>   File "/home/tuong-huy/test_g6k/g6k/setup.py", line 109, in <module>
>     ext_modules=cythonize(
>                 ^^^^^^^^^^
>   File "/home/tuong-huy/miniconda3/envs/env-g6k/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
>     cythonize_one(*args)
>   File "/home/tuong-huy/miniconda3/envs/env-g6k/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
>     raise CompileError(None, pyx_file)
> Cython.Compiler.Errors.CompileError: g6k/siever.pyx
> 

I went to check on previous issues regarding cysignals etc, but so far no luck.
I'm trying to install g6k on Ubuntu 22.04.

**Comment by malb** [comment]
Yes, something broke recently (see also #114) but I hadn't had the time yet to debug. Help welcome :)

**Comment by zlhlovelattice** [comment]
Is there a solution? I also encountered the same problem when installing.

**Comment by malb** [comment]
I didn't manage to reproduce this particular problem (so far)

**Comment by malb** [comment]
Closing this as a duplicate.
