### ISSUE TITLE
How to make the quad double precision available?

### ISSUE THREAD

**Issue by SunZeDong** [fplll/g6k#12]
I read the source code and found that if one wants to run a svp challenge of dimension higher than 200, the quad double precisional library QD is needed. 
To fix this problem, I installed the QD library and set the library path but when running a 200-dimension svp challenge, it still reported a "ValueError: Float type 'dd' unknown".
Again, I found the problem might come from here: 
In fpylll/src/fpylll/config.pyx and fpylll/src/fpylll/config.pxi, HAVE_QD is defined as False
However, when installing g6k in its virtual_env, I have no access to this parameter.
Thanks for your time and consideration.

**Comment by malb** [comment]
Hi, you need to recompile fplll and fpylll so that they pick up QD.

**Comment by SunZeDong** [comment]
> Hi, you need to recompile fplll and fpylll so that they pick up QD.

Thanks a lot. Problem fixed.

**Comment by SunZeDong** [comment]
sour
