### ISSUE TITLE
Run-time issue using multiprocessing with g6k

### ISSUE THREAD

**Issue by DotanGazith** [fplll/g6k#121]
Hello,

I tried to use g6k with Python=92s multiprocessing but faced a huge difference between the run-time of different runs. I ran a version of the "find all short vectors" example and made a test in which I ran in on the same lattice many times. To be more specific:
1. the lattice is of dimension 60
2. I ran 160 instances of it
3. I used 40 workers
4. most of the workers (39) ran out of jobs after 10~12 CPU minutes
5. the last worker is running for nearly a CPU hour and still continues
Is it a feature of g6k having some extreme run times?

Thanks,
Dotan Gazith.

**Comment by malb** [comment]
I'd suspect this instance somehow cannot reach saturation? Did you pick seeds for all instances? Could try to run just that and see if you get warnings?
