### ISSUE TITLE
FPLLL configure fails

### ISSUE THREAD

**Issue by lducas** [fplll/g6k#124]
While running `bootstrap.sh`, I encounter the following error during fplll `configure`.

Full dump:
```
./configure: line 18596: syntax error near unexpected token `LIBQD,'
./configure: line 18596: `  PKG_CHECK_MODULES(LIBQD, qd, have_libqd="yes",'
make: *** No rule to make target 'clean'.  Stop.
Make clean failed in fplll. This is usually because there was an error with either autogen.sh or configure.
Check the logs above - they'll contain more information.
```

I get the same error running `./configure` manually in the subfolder `g6k-env`. 
I do *not* get the error if I run the same in a fresh independent `fplll` folder manually cloned from fplll repository.

**Comment by cr-marcstevens** [comment]
It seems a pkg-config issue. Is it installed on system?

**Comment by lducas** [comment]
Now yes.  Still same behavior.
