### ISSUE TITLE
fpylll.util.ReductionError: infinite loop in babai

### ISSUE THREAD

**Issue by SunZeDong** [fplll/g6k#13]
When using the svp_challenge.py to run some experiments, it always occurs "infinite loop in babai", I check the source code in FPLLL and found problem is caused by the code below:
 if (iter >= 2)
    {
      long new_max_expo = m.get_max_mu_exp(kappa, size_reduction_end);
      if (new_max_expo > max_expo - SIZE_RED_FAILURE_THRESH)
      {
        return set_status(RED_BABAI_FAILURE);
      }
      max_expo = new_max_expo;
    }
which means the coordinate of the GSO matrix needs more precision than the threshold.

How to fix this problem? Is there any parameter to set to choose the precision?
Thanks a lot.

**Comment by malb** [comment]
I'm guessing this is caused by this line: https://github.com/fplll/g6k/blob/plain-sieve/g6k/utils/util.py#L31 You'll need to change it to use more precision such as "ld", "dd", or "mpfr" paired with `FPLLL.set_precision(desired_precision)`
