### ISSUE TITLE
Changing precision cannot fix “infinite loop in babai”error

### ISSUE THREAD

**Issue by SunZeDong** [fplll/g6k#14]
File "src/fpylll/fplll/lll.pyx", line 305, in fpylll.fplll.lll.LLLReduction.__call__
fpylll.util.ReductionError: infinite loop in babai
which is caused by file "util.py", line 44, in load_matrix_file
    bkz.lll_obj()  # to initialize bkz.M etc

I changed the float_type of the GSO matrix M to "ld", "dd" or "mpfr" https://github.com/fplll/g6k/blob/plain-sieve/g6k/utils/util.py#L31, and FPLLL.set_precision(100/200), but neither worked.
the following is my code example:

FPLLL.set_precision(200)
M = GSO.Mat(A, float_type="mpfr", flags=GSO.ROW_EXPO)
bkz = BKZReduction(M)

Have you ever come across this error? Thanks a lot.

**Comment by malb** [comment]
Hard to tell remotely, but try running `LLL.reduction(A)` on your input before constructing the BKZ/GSO objects. `LLL.reduction()` will manage the precision for the initial LLL for you.

**Comment by SunZeDong** [comment]
This method does not seem feasible. The original code in function "load_matrix_file" is:
    **A = IntegerMatrix.from_file(filepath)
    A = LLL.reduction(A)
    A = IntegerMatrix.from_matrix(A, int_type="long")

    M = GSO.Mat(A, float_type="double", flags=GSO.ROW_EXPO)
    bkz = BKZReduction(M)

   if seed is not None:
        FPLLL.set_random_seed(seed)

    if randomize:
        bkz.randomize_block(0, A.nrows, density=A.ncols/4)
        LLL.reduction(A)
        bkz = BKZReduction(A)

    LLL.reduction(A)
    bkz.lll_obj()  # to initialize bkz.M etc

    return A, bkz**

I read the GSO.pyx and found flag GSO.ROW_EXPO works only with double and long double. I changed the float_type and flags and the error "infinite loop in babai" occured again.
The error was caused by the code **bkz.lll_obj()**
What's more, it seems when the lattice dimension is beyond 200, this error occurs.
Thanks for your time and consideration.

**Comment by malb** [comment]
Sorry, can't really see an obvious thing to try remotely.

**Comment by SunZeDong** [comment]
Thanks for your time and consideration.
I commented out the code line "bkz.lll_obj()", the error was fixed and function was still good.

**Comment by MahmoodSpewAfsh** [comment]
Hello I encounter the same problem while using the BKZ reduction. the error occurs as below:

 File "/usr/lib/python3/dist-packages/fpylll/algorithms/bkz.py", line 92, in __call__
    clean = self.tour(params, min_row, max_row, tracer)
  File "/usr/lib/python3/dist-packages/fpylll/algorithms/bkz.py", line 123, in tour
    clean &= self.svp_reduction(kappa, block_size, params, tracer)
  File "/usr/lib/python3/dist-packages/fpylll/algorithms/bkz2.py", line 99, in svp_reduction
    self.svp_preprocessing(kappa, block_size, params, tracer=tracer)
  File "/usr/lib/python3/dist-packages/fpylll/algorithms/bkz2.py", line 69, in svp_preprocessing
    clean &= BKZBase.svp_preprocessing(self, kappa, block_size, params, tracer)
  File "/usr/lib/python3/dist-packages/fpylll/algorithms/bkz.py", line 147, in svp_preprocessing
    self.lll_obj(lll_start, lll_start, kappa + block_size)
  File "src/fpylll/fplll/lll.pyx", line 305, in fpylll.fplll.lll.LLLReduction.__call__
fpylll.util.ReductionError: b'infinite loop in babai'

what should I do?
