### ISSUE TITLE
Reduce data in traces

### ISSUE THREAD

**Issue by malb** [fplll/g6k#28]
The current amount collected makes them essentially unusable.

**Comment by lducas** [comment]
Can you comment on what data does the tracer accumulates ? I thought this issues would only arise when a lot of small calls are made, but Wessel just reported that it lost about an hour to single-threaded tracing during a signle (very large !) pump.

**Comment by WvanWoerden** [comment]
I blamed the tracer too soon. The hour loss was due to https://github.com/fplll/g6k/pull/30
The overhead of the tracer seems to be about 50 seconds for a single large pump.
