### ISSUE TITLE
ImportError: No module named siever_params

### ISSUE THREAD

**Issue by kanav99** [fplll/g6k#49]
Hello! I wanted to try out this package but I get 
```
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_svp_challenge.py:2: in <module>
    from svp_challenge import asvp_kernel
svp_challenge.py:16: in <module>
    from g6k.algorithms.workout import workout
g6k/__init__.py:4: in <module>
    from .siever_params import SieverParams # noqa
E   ImportError: No module named siever_params
```

Probably I need to make a file `siever_params.py` but what is the example format of this file? This error is raised in tests ran using `python -m pytest` command too.

**Comment by joerowell** [comment]
Did you run ./bootstrap.sh in the topmost directory? If not, you'll need to
do this in order to get Cython to compile the right files.

If you did, this looks like you haven't activated the virtual environment.
You do this by running 'source ./activate' in the topmost directory.

**Comment by lducas** [comment]
@kanav99 may we close this one ?

**Comment by kanav99** [comment]
I apologize @lducas @joerowell for not replying, I was able to run after changing to python3 and following your instructions. Thank you so much, you may close the issue.
