### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'accumulate'

### ISSUE THREAD

**Issue by MiBu84** [fplll/g6k#6]
Hi,
installation seemed to work fine by copying and executing the commands from the instructions in the virtualenv running in Ubuntu.

_python -m pytest_ only returns two warnings, now errors.
_./svp_exact_find_norm.py 50 -u 60 --workers 4 --challenge-seed 0 1 2_ seems to work correctly and returns the correct norms.

_./svp_exact.py 50 -u 60 --workers 3 --challenge-seed 0 1 2_
Crashes after several seconds with:
_Traceback (most recent call last):
  File "./svp_exact.py", line 150, in <module>
    svp()
  File "./svp_exact.py", line 140, in svp
    avr_db, max_db = db_stats(stat)
  File "/home/mb31simi/g6k/g6k/utils/util.py", line 229, in db_stats
    max_dbs += stat.accumulate("|db|",
AttributeError: 'Node' object has no attribute 'accumulate'_

Python:   2.7.6
gcc 4.8.2

**Comment by malb** [comment]
Maybe your copy of fpylll is too old?

**Comment by MiBu84** [comment]
Thank you very much. That solves the problem. Sorry for the question. I didn't recognise the old fpylll in the environment variables.
