### ISSUE TITLE
What's the difference between "--workers" and "--threads" in the command line arguments00

### ISSUE THREAD

**Issue by SunZeDong** [fplll/g6k#7]
After reading the g6k introduction and its source code, I cannot figure out the difference between "--workers" and "--threads".
Is that "--workers" means number of parallel experiments but independent to each other while "--threads" means number of threads to run the same experiment?
for example, ./svp_challenge.py 100 --workers 4 equals to run 4 independent svp challenges of dimension 100 while ./svp_challenge.py 100 --threads equals to run 4 threads to solve 100-dimension svp challenge parallelly?
By the way, ./svp_challenge.py --help seems to tell that it doesn't support "--thread".

**Comment by malb** [comment]
Yep, that's it, see https://github.com/fplll/g6k/blob/master/g6k/utils/cli.py#L155 The help of ``--help`` is not meant to be comprehensive.

**Comment by malb** [comment]
PS: you can use `--show-defaults` to get a sense of supported parameters
