### ISSUE TITLE
AVX2 v Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz

### ISSUE THREAD

**Issue by malb** [fplll/g6k#72]
We might simply accept this but G6K won't compile/work any longer on a CPU without AVX2:

```
.../include/avxintrin.h:1266:1: error: inlining failed in call to always_inline '__m256i _mm256_set_epi16(short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int)': target specific option mismatch
 _mm256_set_epi16 (short __q15, short __q14, short __q13, short __q12,
 ^~~~~~~~~~~~~~~~
In file included from fht_lsh.cpp:3:0:
fht_lsh.h:23:51: note: called from here
 const __m256i mixmask_threshold = _mm256_set_epi16(
                                   ~~~~~~~~~~~~~~~~^
     0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555, 0x5555,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     0xAAAA, 0xAAAA, 0xAAAA, 0xAAAA, 0xAAAA, 0xAAAA, 0xAAAA, 0xAAAA);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:13: fht_lsh.o] Error 1

```

**Comment by cr-marcstevens** [comment]
@malb I think the goal now is:
1) to detect avx2 compile support at build time => disable bdgl if not
2) add avx2 cpu support runtime detection into bdgl => throw error if no avx2 cpu support.

**Comment by malb** [comment]
Could we not fall back to something slower if AVX2 is not available? But otherwise, I agree.

**Comment by themaddoctor** [comment]
I normally have no problems building packages on my linux system, but here is what happens with g6k-fix-autoconf:

```
$ unzip g6k-avx2-fix-autoconf.zip
$ cd g6k-avx2-fix-autoconf
$ aclocal
$ autoconf
$ ./configure
configure: error: cannot run /bin/sh ./../../config.sub
```

**Comment by malb** [comment]
I just did:
```
$ unp g6k-avx2-fix.zip # we merged the autoconf stuff into this one now
$ python setup.py build # which runs autoreconf -i, ./configure, make
```

and it just works™ here.

**Comment by cr-marcstevens** [comment]
Nice work! How do you go about passing options to configure, like the `--native`?

**Comment by malb** [comment]
At the moment `python setup.py build_ext` only passes through `-jX` to make and nothing to configure. Note though that if you run `configure` before, e.g. with `configure --enable-native` (which is the default) then this will be reused. The logic is dumb: just check if `Makefile` exists.

**Comment by malb** [comment]
I mean we could loop through the parameters and string match against `./configure --help` but do we want to?

**Comment by malb** [comment]
In the meantime, this one should allow you to avoid aclocal/autoreconfig etc [G6K-0.1.1.tar.gz](https://github.com/fplll/g6k/files/6445909/G6K-0.1.1.tar.gz)

**Comment by joerowell** [comment]
I've tested the version of g6k that's currently on master on the machine in question and it now works correctly. Closing this.
