### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by themaddoctor** [fplll/g6k#81]

**Comment by themaddoctor** [comment]
Sorry I don't have all the right debugging tools installed. All of the examples in README.md give output similar to this:

lwe_challenge.py n --lwe/alpha alpha
------------------------------------------------------------------------
/usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x7f18)[0x7fb25b1daf18]
/usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x7fb8)[0x7fb25b1dafb8]
/usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x9e6b)[0x7fb25b1dce6b]
/lib64/libpthread.so.0(+0xf820)[0x7fb265359820]
/usr/lib/python3.7/site-packages/g6k/siever_params.cpython-37m-x86_64-linux-gnu.so(+0x14638)[0x7fb25922d638]
/lib64/ld-linux-x86-64.so.2(+0xe7ea)[0x7fb265ad47ea]
/lib64/ld-linux-x86-64.so.2(+0xe8d3)[0x7fb265ad48d3]
/lib64/ld-linux-x86-64.so.2(+0x12a38)[0x7fb265ad8a38]
/lib64/ld-linux-x86-64.so.2(+0xe674)[0x7fb265ad4674]
/lib64/ld-linux-x86-64.so.2(+0x1222b)[0x7fb265ad822b]
/lib64/libdl.so.2(+0x101b)[0x7fb26514701b]
/lib64/ld-linux-x86-64.so.2(+0xe674)[0x7fb265ad4674]
/lib64/libdl.so.2(+0x15cd)[0x7fb2651475cd]
/lib64/libdl.so.2(dlopen+0x31)[0x7fb2651470b1]
/usr/lib64/libpython3.7m.so.1.0(_PyImport_FindSharedFuncptr+0x180)[0x7fb26573ee80]
/usr/lib64/libpython3.7m.so.1.0(_PyImport_LoadDynamicModuleWithSpec+0x14a)[0x7fb26570b11a]
/usr/lib64/libpython3.7m.so.1.0(+0x1a21df)[0x7fb2657091df]
/usr/lib64/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x2d1)[0x7fb2656025e1]
/usr/lib64/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x25)[0x7fb265602675]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7e00)[0x7fb2655d92e0]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x8f)[0x7fb265601a5f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x8ee6)[0x7fb2655da3c6]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7cba)[0x7fb2655d919a]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x28f)[0x7fb2656019bf]
/usr/lib64/libpython3.7m.so.1.0(+0x9bd22)[0x7fb265602d22]
/usr/lib64/libpython3.7m.so.1.0(_PyObject_CallMethodIdObjArgs+0xa5)[0x7fb265602fd5]
/usr/lib64/libpython3.7m.so.1.0(PyImport_ImportModuleLevelObject+0x4df)[0x7fb26570a25f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7ed9)[0x7fb2655d93b9]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(PyEval_EvalCodeEx+0x3e)[0x7fb2656eec4e]
/usr/lib64/libpython3.7m.so.1.0(PyEval_EvalCode+0x1b)[0x7fb2656eec7b]
/usr/lib64/libpython3.7m.so.1.0(+0x184e7d)[0x7fb2656ebe7d]
/usr/lib64/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallDict+0x2d1)[0x7fb2656025e1]
/usr/lib64/libpython3.7m.so.1.0(_PyCFunction_FastCallDict+0x25)[0x7fb265602675]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7e00)[0x7fb2655d92e0]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x8f)[0x7fb265601a5f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x8ee6)[0x7fb2655da3c6]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7cba)[0x7fb2655d919a]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x28f)[0x7fb2656019bf]
/usr/lib64/libpython3.7m.so.1.0(+0x9bd22)[0x7fb265602d22]
/usr/lib64/libpython3.7m.so.1.0(_PyObject_CallMethodIdObjArgs+0xa5)[0x7fb265602fd5]
/usr/lib64/libpython3.7m.so.1.0(PyImport_ImportModuleLevelObject+0x4df)[0x7fb26570a25f]
/usr/lib64/libpython3.7m.so.1.0(+0x1834e4)[0x7fb2656ea4e4]
/usr/lib64/libpython3.7m.so.1.0(PyCFunction_Call+0x108)[0x7fb265603d28]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7e00)[0x7fb2655d92e0]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x8f)[0x7fb265601a5f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x28f)[0x7fb2656019bf]
/usr/lib64/libpython3.7m.so.1.0(+0x9bd22)[0x7fb265602d22]
/usr/lib64/libpython3.7m.so.1.0(_PyObject_CallMethodIdObjArgs+0xa5)[0x7fb265602fd5]
/usr/lib64/libpython3.7m.so.1.0(PyImport_ImportModuleLevelObject+0x4df)[0x7fb26570a25f]
/usr/lib64/libpython3.7m.so.1.0(+0x1834e4)[0x7fb2656ea4e4]
/usr/lib64/libpython3.7m.so.1.0(PyCFunction_Call+0x108)[0x7fb265603d28]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7e00)[0x7fb2655d92e0]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x8f)[0x7fb265601a5f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x6a45)[0x7fb2655d7f25]
/usr/lib64/libpython3.7m.so.1.0(+0x693df)[0x7fb2655d03df]
/usr/lib64/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x28f)[0x7fb2656019bf]
/usr/lib64/libpython3.7m.so.1.0(+0x9bd22)[0x7fb265602d22]
/usr/lib64/libpython3.7m.so.1.0(_PyObject_CallMethodIdObjArgs+0xa5)[0x7fb265602fd5]
/usr/lib64/libpython3.7m.so.1.0(PyImport_ImportModuleLevelObject+0x4df)[0x7fb26570a25f]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x7ed9)[0x7fb2655d93b9]
/usr/lib64/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0xa7b)[0x7fb2656eeb4b]
/usr/lib64/libpython3.7m.so.1.0(PyEval_EvalCodeEx+0x3e)[0x7fb2656eec4e]
/usr/lib64/libpython3.7m.so.1.0(PyEval_EvalCode+0x1b)[0x7fb2656eec7b]
/usr/lib64/libpython3.7m.so.1.0(PyRun_FileExFlags+0xaa)[0x7fb265722aaa]
/usr/lib64/libpython3.7m.so.1.0(PyRun_SimpleFileExFlags+0xdf)[0x7fb265722bff]
/usr/lib64/libpython3.7m.so.1.0(+0x1de7ac)[0x7fb2657457ac]
/usr/lib64/libpython3.7m.so.1.0(_Py_UnixMain+0x6a)[0x7fb265745e6a]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb2648b8b15]
/usr/bin/python3[0x4006de]
------------------------------------------------------------------------
Attaching gdb to process id 24130.
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fb265359429 in waitpid () from /lib64/libpthread.so.0

Stack backtrace
---------------
No symbol table info available.
#1  0x00007fb25b1d99d2 in print_enhanced_backtrace ()
   from /usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so
No symbol table info available.
#2  0x00007fb25b1daff5 in sigdie ()
   from /usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so
No symbol table info available.
#3  0x00007fb25b1dce6b in cysigs_signal_handler ()
   from /usr/lib/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so
No symbol table info available.
#4  <signal handler called>
No symbol table info available.
#5  0x00007fb25922d638 in _GLOBAL__sub_I_fht_lsh.cpp ()
   from /usr/lib/python3.7/site-packages/g6k/siever_params.cpython-37m-x86_64-linux-gnu.so
No symbol table info available.
#6  0x00007fb265ad47ea in call_init.part () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#7  0x00007fb265ad48d3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#8  0x00007fb265ad8a38 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#9  0x00007fb265ad4674 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#10 0x00007fb265ad822b in _dl_open () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#11 0x00007fb26514701b in dlopen_doit () from /lib64/libdl.so.2
No symbol table info available.
#12 0x00007fb265ad4674 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#13 0x00007fb2651475cd in _dlerror_run () from /lib64/libdl.so.2
No symbol table info available.
#14 0x00007fb2651470b1 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
No symbol table info available.
#15 0x00007fb26573ee80 in _PyImport_FindSharedFuncptr ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#16 0x00007fb26570b11a in _PyImport_LoadDynamicModuleWithSpec ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#17 0x00007fb2657091df in _imp_create_dynamic ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#18 0x00007fb2656025e1 in _PyMethodDef_RawFastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#19 0x00007fb265602675 in _PyCFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#20 0x00007fb2655d92e0 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#21 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#22 0x00007fb265601a5f in _PyFunction_FastCallKeywords ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#23 0x00007fb2655da3c6 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#24 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#25 0x00007fb2655d919a in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#26 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#27 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#28 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#29 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#30 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#31 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#32 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#33 0x00007fb2656019bf in _PyFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#34 0x00007fb265602d22 in object_vacall () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#35 0x00007fb265602fd5 in _PyObject_CallMethodIdObjArgs ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#36 0x00007fb26570a25f in PyImport_ImportModuleLevelObject ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#37 0x00007fb2655d93b9 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#38 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#39 0x00007fb2656eec4e in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#40 0x00007fb2656eec7b in PyEval_EvalCode ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#41 0x00007fb2656ebe7d in builtin_exec () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#42 0x00007fb2656025e1 in _PyMethodDef_RawFastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#43 0x00007fb265602675 in _PyCFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#44 0x00007fb2655d92e0 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#45 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#46 0x00007fb265601a5f in _PyFunction_FastCallKeywords ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#47 0x00007fb2655da3c6 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#48 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#49 0x00007fb2655d919a in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#50 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#51 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#52 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#53 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#54 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#55 0x00007fb2656019bf in _PyFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#56 0x00007fb265602d22 in object_vacall () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#57 0x00007fb265602fd5 in _PyObject_CallMethodIdObjArgs ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#58 0x00007fb26570a25f in PyImport_ImportModuleLevelObject ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#59 0x00007fb2656ea4e4 in builtin___import__ ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#60 0x00007fb265603d28 in PyCFunction_Call ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#61 0x00007fb2655d92e0 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#62 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#63 0x00007fb265601a5f in _PyFunction_FastCallKeywords ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#64 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#65 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#66 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#67 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#68 0x00007fb2656019bf in _PyFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#69 0x00007fb265602d22 in object_vacall () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#70 0x00007fb265602fd5 in _PyObject_CallMethodIdObjArgs ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#71 0x00007fb26570a25f in PyImport_ImportModuleLevelObject ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#72 0x00007fb2656ea4e4 in builtin___import__ ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#73 0x00007fb265603d28 in PyCFunction_Call ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#74 0x00007fb2655d92e0 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#75 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#76 0x00007fb265601a5f in _PyFunction_FastCallKeywords ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#77 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#78 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#79 0x00007fb2655d7f25 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#80 0x00007fb2655d03df in function_code_fastcall ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#81 0x00007fb2656019bf in _PyFunction_FastCallDict ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#82 0x00007fb265602d22 in object_vacall () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#83 0x00007fb265602fd5 in _PyObject_CallMethodIdObjArgs ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#84 0x00007fb26570a25f in PyImport_ImportModuleLevelObject ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#85 0x00007fb2655d93b9 in _PyEval_EvalFrameDefault ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#86 0x00007fb2656eeb4b in _PyEval_EvalCodeWithName ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#87 0x00007fb2656eec4e in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#88 0x00007fb2656eec7b in PyEval_EvalCode ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#89 0x00007fb265722aaa in PyRun_FileExFlags ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#90 0x00007fb265722bff in PyRun_SimpleFileExFlags ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#91 0x00007fb2657457ac in pymain_main.constprop ()
   from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#92 0x00007fb265745e6a in _Py_UnixMain () from /usr/lib64/libpython3.7m.so.1.0
No symbol table info available.
#93 0x00007fb2648b8b15 in __libc_start_main () from /lib64/libc.so.6
No symbol table info available.
#94 0x00000000004006de in _start ()
No symbol table info available.
Traceback (most recent call last):
  File "<string>", line 25, in <module>
ImportError: No module named Cython.Debugger
Error while executing Python code.

Your system GDB uses an incompatible version of Python.
Install gdb for enhanced tracebacks.
------------------------------------------------------------------------
Unhandled SIGILL: An illegal instruction occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
Illegal instruction

**Comment by malb** [comment]
Maybe same as https://github.com/fplll/g6k/issues/72 ?

**Comment by joerowell** [comment]
@themaddoctor once the PR is merged, could you please confirm that this fixes your problem? It isn't quite ready to go (see e.g the comment on the default flags), but this should go some way towards fixing the bug.

**Comment by themaddoctor** [comment]
Sure. But could you post a comment when the merge takes place, so that I know that it happened? Thanks!

**Comment by malb** [comment]
You can subscribe to PRs and get notified when there's movement on them.

**Comment by themaddoctor** [comment]
I subscribed to the thread in "conversation" on PR 82. Hope that's what you meant.

**Comment by joerowell** [comment]
@themaddoctor can you confirm that the version currently on master fixes this issue?
