### ISSUE TITLE
scipy?

### ISSUE THREAD

**Issue by themaddoctor** [fplll/g6k#85]
scipy wasn't listed in requirements.txt, but although I was able to compile (had to run aclocal and autoconf before
autoreconf), and although there were no complaints about it when building g6k, this is the result:
```
$bkz.py 180 --bkz/betas 60:95:1 --bkz/pre_beta 59 --trials 8 --workers 8
Traceback (most recent call last):
  File "/usr/bin/bkz.py", line 39, in <module>
    from g6k.algorithms.bkz import naive_bkz_tour, pump_n_jump_bkz_tour, slide_tour
  File "/usr/lib/python3.7/site-packages/g6k/__init__.py", line 24, in <module>
    from .siever import Siever  # noqa
  File "g6k/siever.pyx", line 29, in init g6k.siever
ModuleNotFoundError: No module named 'scipy'
```
So while I am no longer getting any "illegal instruction" errors, I cannot test any further at this time.

**Comment by joerowell** [comment]
That's very bizarre. The ``requirements.txt`` file hasn't changed in the last 9 months, and even the version on the ``avx2-fix`` branch has ``scipy`` listed (see https://github.com/fplll/g6k/blob/f65e3a2db58ca876ddaa4b9d201a20a50702b8b2/requirements.txt#L9). 

In any case: you should be able to fix this by running ``python -m pip install scipy`` inside your virtual environment.

**Comment by malb** [comment]
https://github.com/fplll/g6k/blob/master/requirements.txt#L9
