### ISSUE TITLE
line 197 in g6k/utils/cli.py has something wrong

### ISSUE THREAD

**Issue by G8-0tto** [fplll/g6k#93]
when I use the lwe_challenge.py, it reports me :

usage: a.py [-h] [-u UPPER_BOUND] [-s STEP_SIZE] [-t TRIALS] [-w WORKERS] [-p]
            [-S SEED] [--dry-run] [--show-defaults] [--loglvl LOGLVL]
            [--log-filename LOG_FILENAME] [--profile PROFILE]
            lower_bound
a.py: error: the following arguments are required: lower_bound

Then I turn to read g6k/utils/cli.py, in line 197 :

**parser.add_argument('lower_bound', type=int, 
help="lowest lattice dimension to consider (inclusive)")**    
parser.add_argument('-u', '--upper-bound', type=int, dest="upper_bound", default=0,                        
help="upper bound on lattice dimension to consider (exclusive)")

rewrite it to :

**parser.add_argument('-l', '--lower_bound', type=int, dest="lower_bound", default=0,
                        help="lowest lattice dimension to consider (inclusive)")**    

as the same as upper_bound

it works : )

**Comment by malb** [comment]
It looks fine to me as is.
