### ISSUE TITLE
The reference of determining lwechallenge samples amount m  in lwe_estimation.py 

### ISSUE THREAD

**Issue by Summwer** [fplll/g6k#95]
Hello, developer,
    Could you plz tell me The reference of determining lwe samples amount m in function `decoupler()` of `lwe_estimation.py` ?

**Comment by malb** [comment]
The strategy pursued was proposed in

- Erdem Alkim, Léo Ducas, Thomas Pöppelmann, Peter Schwabe: Post-quantum Key Exchange - A New Hope. USENIX Security Symposium 2016: 327-343

And analysed in:

- Martin R. Albrecht, Florian Göpfert, Fernando Virdia, Thomas Wunderer: Revisiting the Expected Cost of Solving uSVP and Applications to LWE. ASIACRYPT (1) 2017: 297-322
- Eamonn W. Postlethwaite, Fernando Virdia: On the Success Probability of Solving Unique SVP via BKZ. Public Key Cryptography (1) 2021: 68-98
