### ISSUE TITLE
Hello, developer！

### ISSUE THREAD

**Issue by heyanheyan** [fplll/g6k#96]
ValueError: Float type 'dd' unknown. Hello, developer！How to solve it?

**Comment by malb** [comment]
I've just created https://github.com/fplll/fpylll/wiki/Float-Type-unknown to answer this (since this keeps coming up)

**Comment by heyanheyan** [comment]
ok,thank you very much!!!

**Comment by heyanheyan** [comment]
Hello, developer！Is it OK to install qdlib-dev？

**Comment by joerowell** [comment]
Yes, it's fine to install ``libqd-dev`` if it exists for your distribution (see e.g https://packages.debian.org/stretch/libqd-dev)
